[package]
name = "rust_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = 1

[dependencies]
colored = "2.1.0"
petgraph = "0.6.4"
rand = "0.8.5"
regex = "1.10.3"
